PartyNeighbors.MVC/Controllers/PartyItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PartyNeighbors.Data;
using PartyNeighbors.Models.PartyItem;
using PartyNeighbors.Services;

namespace PartyNeighbors.MVC.Controllers
{
    public class PartyItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private PartyItemService _partyItemService;
        private Guid _userId;


        // GET: PartyItems
        public ActionResult Index()
        {
            return View(db.PartyItems.ToList());
        }

        // GET: PartyItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartyItem partyItem = db.PartyItems.Find(id);
            if (partyItem == null)
            {
                return HttpNotFound();
            }
            return View(partyItem);
        }

        // GET: PartyItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PartyItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PartyItemCreate partyItem)
        {
            if (ModelState.IsValid)
            {
                _userId = Guid.Parse(User.Identity.GetUserId());
                _partyItemService = new PartyItemService(_userId);
                _partyItemService.CreatePartyItem(partyItem);
                return RedirectToAction("Index");
            }

            return View(partyItem);
        }

        // GET: PartyItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartyItem partyItem = db.PartyItems.Find(id);
            if (partyItem == null)
            {
                return HttpNotFound();
            }
            return View(partyItem);
        }

        // POST: PartyItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PartyItemEdit partyItem)
        {
            if (ModelState.IsValid)
            {
                _userId = Guid.Parse(User.Identity.GetUserId());
                _partyItemService = new PartyItemService(_userId);
                _partyItemService.EditPartyItem(partyItem);
                return RedirectToAction("Index");
            }
            return View(partyItem);
        }

        // GET: PartyItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PartyItem partyItem = db.PartyItems.Find(id);
            if (partyItem == null)
            {
                return HttpNotFound();
            }
            return View(partyItem);
        }

        // POST: PartyItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PartyItem partyItem = db.PartyItems.Find(id);
            db.PartyItems.Remove(partyItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PartyNeighbors.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Party Neighbors Landing</title>
    <link href="https://fonts.googleapis.com/css2?family=Audiowide&family=Fredericka+the+Great&family=Kalam:wght@300&family=Monoton&family=Permanent+Marker&family=Rock+Salt&display=swap" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Party 'N", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li><a href="#" id="aboutUs">About Us</a></li>
                    <li><a href="#" id="contactUs">Contact Us</a></li>
                    <li>@*@Html.ActionLink("Contact", "Contact", "Home")*@</li>
                    <li>@Html.ActionLink("Residents", "Index", "Residents")</li>
                    <li>@Html.ActionLink("Locations", "Index", "Locations")</li>
                    @*<li>@Html.ActionLink("Party Items", "Index", "PartyItems")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <div class="navbar navbar-inverse navbar-fixed-bottom footer">
            <p>&copy; @DateTime.Now.Year - Party Neighbors</p>
        </div>
    </div>

    <div class="modal fade" id="AboutModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h4 class="modal-title">Get to Know Us!</h4>
                </div>
                <div class="modal-body">
                    <p>
                        At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti
                        quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia
                        deserunt mollitia animi, id est laborum et dolorum fuga.
                    </p>
                </div>
                <div class="modal-footer">
                    <div class="btn btn-secondary close" data-dismiss="modal">Close</div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="ContactModal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h4 class="modal-title">Reach out to us!</h4>
                </div>
                <div class="modal-body">
                    <div class="contact" id="phone">
                        <div class="control-label col-md-2">Phone: </div>
                        <div class="col-md-4 contactInfo">917-379-9137</div>
                    </div>
                    <div class="contact" id="email">
                        <div class="control-label col-md-2">Email: </div>
                        <div class="col-md-4 contactInfo">assistance@partyn.com</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="btn btn-secondary close" data-dismiss="modal">Close</div>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {
            $('#aboutUs').click(function () {
                $('#AboutModal').modal('show')
            });

            $('#contactUs').click(function () {
                $('#ContactModal').modal('show')
            });
        });
    </script>
</body>
</html>